SELECT count(*) as namebasics FROM public.namebasics
SELECT count(*) as nameknownfortitles FROM public.nameknownfortitles
SELECT count(*) as nameprimaryprofession FROM public.nameprimaryprofession
SELECT count(*) as titleakas FROM public.titleakas
SELECT count(*) as titlebasics FROM public.titlebasics
SELECT count(*) as titlebasicsgenres FROM public.titlebasicsgenres
SELECT count(*) as titledirectors FROM public.titledirectors
SELECT count(*) as titleepisodes FROM public.titleepisodes
SELECT count(*) as titleprincipals FROM public.titleprincipals
SELECT count(*) as titleratings FROM public.titleratings
SELECT count(*) as titlewriters FROM public.titlewriters